# Generated by Django 3.2 on 2021-10-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_alter_vehicleyear_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='price',
            field=models.IntegerField(default=100000000),
        ),
    ]
