# Generated by Django 3.2 on 2021-10-18 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20211018_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicletype',
            name='brand_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='restapi.vehiclebrand'),
        ),
    ]
