# Generated by Django 3.2 on 2021-10-18 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_alter_vehicletype_brand_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemodel',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model', to='restapi.vehicletype'),
        ),
    ]
